[project]
name = 'DAO-Managed-Layaway-Purchase-Contracts'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.DAO-Managed-Layaway-Purchase]
path = 'contracts/DAO-Managed-Layaway-Purchase.clar'
clarity_version = 3
epoch = 3.1

[contracts.buyer-reputation]
path = 'contracts/buyer-reputation.clar'
clarity_version = 3
epoch = 3.1

[contracts.dispute-resolution]
path = 'contracts/dispute-resolution.clar'
clarity_version = 3
epoch = 3.1
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
